const STATE_KEY='lyphTitleCompetition_v3',LEGACY_KEY='doctorLawExam_v1',SESSION_SIZE=50;
let bank=null,questionsById=new Map(),state=null,pendingMulti=new Set(),wrongFilter='all',touchStart=null,toastTimer=null;
const $=id=>document.getElementById(id),letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ',clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function emptyState(){return{version:3,answered:0,correct:0,wrong:{},seen:{},moduleStats:{},activeSession:null,migratedLegacy:false}}
function loadState(){try{state={...emptyState(),...JSON.parse(localStorage.getItem(STATE_KEY)||'null')}}catch{state=emptyState()}state.wrong||={};state.seen||={};state.moduleStats||={};if(!state.migratedLegacy)migrateLegacy()}
function migrateLegacy(){try{const legacy=JSON.parse(localStorage.getItem(LEGACY_KEY)||'null');if(legacy){state.answered=Math.max(state.answered,Number(legacy.answered)||0);state.correct=Math.max(state.correct,Number(legacy.correct)||0);Object.entries(legacy.wrong||{}).forEach(([id,count])=>{const qid=`physician-curated-${String(id).padStart(3,'0')}`;state.wrong[qid]=Math.max(state.wrong[qid]||0,Number(count)||1)});Object.keys(legacy.todayAnswers||{}).forEach(id=>state.seen[`physician-curated-${String(id).padStart(3,'0')}`]=true)}}catch{}state.migratedLegacy=true;persist()}
function persist(){localStorage.setItem(STATE_KEY,JSON.stringify(state))}
function moduleById(id){return bank.modules.find(m=>m.id===id)}function moduleQuestions(id){return bank.questions.filter(q=>q.moduleId===id)}function moduleStat(id){return state.moduleStats[id]||{answered:0,correct:0}}function currentSession(){return state.activeSession}function currentQuestion(){const s=currentSession();return s?questionsById.get(s.questionIds[s.pos]):null}
function seededShuffle(values,seed){const result=[...values];let h=2166136261;for(const c of seed){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}const rand=()=>{h+=0x6D2B79F5;let t=h;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296};for(let i=result.length-1;i>0;i--){const j=Math.floor(rand()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result}
function createSession(moduleId,mode='module'){const source=mode==='wrong'?bank.questions.filter(q=>state.wrong[q.id]&&(moduleId==='all'||q.moduleId===moduleId)):moduleQuestions(moduleId);const seed=`${new Date().toISOString().slice(0,10)}-${moduleId}-${state.answered}-${mode}`;const wrong=seededShuffle(source.filter(q=>state.wrong[q.id]),seed+'w').sort((a,b)=>(state.wrong[b.id]||0)-(state.wrong[a.id]||0)),fresh=seededShuffle(source.filter(q=>!state.seen[q.id]&&!state.wrong[q.id]),seed+'f'),review=seededShuffle(source.filter(q=>state.seen[q.id]&&!state.wrong[q.id]),seed+'r'),selected=[...wrong,...fresh,...review].slice(0,SESSION_SIZE);if(!selected.length){showToast(mode==='wrong'?'目前没有可复习的错题':'该题库暂无题目');return false}state.activeSession={moduleId:moduleId==='all'?selected[0].moduleId:moduleId,mode,questionIds:selected.map(q=>q.id),pos:0,answers:{},startedAt:new Date().toISOString()};persist();pendingMulti.clear();showView('quiz');return true}
function resumeSession(){if(state.activeSession)showView('quiz')}
function renderHome(){$('totalAnswered').textContent=state.answered;$('homeRate').textContent=state.answered?`${Math.round(state.correct/state.answered*100)}%`:'—';$('homeWrong').textContent=Object.keys(state.wrong).length;$('bankTotal').textContent=`${bank.questions.length} 题`;$('headerSub').textContent=`10 类法规与制度 · ${bank.questions.length} 题 · 单选 + 多选`;const s=state.activeSession;$('resumeBox').classList.toggle('hidden',!s);if(s){$('resumeTitle').textContent=moduleById(s.moduleId)?.name||'错题专项';$('resumeMeta').textContent=`第 ${s.pos+1} / ${s.questionIds.length} 题`}$('moduleGrid').innerHTML=bank.modules.map(m=>{const seen=moduleQuestions(m.id).filter(q=>state.seen[q.id]).length,progress=m.questionCount?Math.round(seen/m.questionCount*100):0;return`<button class="module-card" style="--accent:${m.accent}" data-module="${m.id}"><span class="module-order">${String(m.order).padStart(2,'0')}</span><h3>${m.name}</h3><div class="module-meta">${m.questionCount} 题 · ${m.singleCount} 单选 · ${m.multipleCount} 多选</div><div class="module-bottom"><b>开始训练</b><span class="mini-progress"><i style="width:${progress}%"></i></span></div></button>`}).join('')}
function renderQuestion(){const s=currentSession(),q=currentQuestion();if(!s||!q){showView('home');return}const m=moduleById(q.moduleId),saved=s.answers[q.id],answered=Boolean(saved?.submitted);pendingMulti=new Set(answered?saved.selected:[]);$('quizModule').textContent=m.name;$('quizCounter').textContent=`第 ${s.pos+1} / ${s.questionIds.length} 题`;$('quizProgress').style.width=`${(s.pos+1)/s.questionIds.length*100}%`;$('typeBadge').textContent=q.type==='multiple'?'多选':'单选';$('questionRef').textContent=q.ref;$('questionText').textContent=q.question;$('multiHint').classList.toggle('hidden',q.type!=='multiple');$('optionList').innerHTML=q.options.map((o,i)=>{const selected=answered?saved.selected.includes(i):pendingMulti.has(i),correct=answered&&q.answers.includes(i),wrong=answered&&selected&&!correct,classes=['option',selected?'selected':'',correct?'correct':'',wrong?'wrong':''].filter(Boolean).join(' ');return`<button class="${classes}" data-option="${i}" ${answered?'disabled':''}><span class="letter">${letters[i]}.</span><span>${escapeHtml(o)}</span></button>`}).join('');$('submitMultiple').classList.toggle('hidden',q.type!=='multiple'||answered);$('submitMultiple').disabled=pendingMulti.size===0;$('explanation').classList.toggle('hidden',!answered);if(answered){$('explanation').className=`explanation ${saved.correct?'good':'bad'}`;$('explanation').innerHTML=`<b>${saved.correct?'回答正确':'回答错误'} · 正确答案 ${q.answers.map(i=>letters[i]).join('、')}</b><br>${escapeHtml(q.explanation)}`}$('prevButton').disabled=s.pos===0;$('nextButton').disabled=!answered;$('nextButton').textContent=s.pos===s.questionIds.length-1?'完成本轮':'下一题';window.scrollTo({top:0,behavior:'smooth'})}
function toggleOption(index){const q=currentQuestion(),s=currentSession();if(!q||s.answers[q.id]?.submitted)return;if(q.type==='single'){submitAnswer([index]);return}pendingMulti.has(index)?pendingMulti.delete(index):pendingMulti.add(index);document.querySelector(`[data-option="${index}"]`)?.classList.toggle('selected',pendingMulti.has(index));$('submitMultiple').disabled=pendingMulti.size===0}
function arraysEqual(a,b){const x=[...a].sort((m,n)=>m-n),y=[...b].sort((m,n)=>m-n);return x.length===y.length&&x.every((v,i)=>v===y[i])}
function submitAnswer(selected){const s=currentSession(),q=currentQuestion();if(!s||!q||s.answers[q.id]?.submitted)return;selected=[...new Set(selected)].sort((a,b)=>a-b);const correct=arraysEqual(selected,q.answers);s.answers[q.id]={selected,correct,submitted:true,at:new Date().toISOString()};state.seen[q.id]=true;state.answered++;if(correct)state.correct++;const stats=state.moduleStats[q.moduleId]||{answered:0,correct:0};stats.answered++;if(correct)stats.correct++;state.moduleStats[q.moduleId]=stats;if(correct){if(state.wrong[q.id]){state.wrong[q.id]--;if(state.wrong[q.id]<=0)delete state.wrong[q.id]}}else state.wrong[q.id]=(state.wrong[q.id]||0)+1;persist();renderQuestion()}
function moveQuestion(delta){const s=currentSession();if(!s)return;if(delta>0){const q=currentQuestion();if(!s.answers[q.id]?.submitted){showToast('请先作答，再进入下一题');return}if(s.pos===s.questionIds.length-1){completeSession();return}}s.pos=clamp(s.pos+delta,0,s.questionIds.length-1);persist();renderQuestion()}
function completeSession(){state.activeSession=null;persist();showToast('本轮训练完成');showView('home')}
function renderWrong(){const all=bank.questions.filter(q=>state.wrong[q.id]),used=new Set(all.map(q=>q.moduleId));$('wrongFilters').innerHTML=[{id:'all',name:'全部'},...bank.modules.filter(m=>used.has(m.id))].map(x=>`<button class="${wrongFilter===x.id?'active':''}" data-wrong-filter="${x.id}">${x.name}</button>`).join('');const filtered=all.filter(q=>wrongFilter==='all'||q.moduleId===wrongFilter).sort((a,b)=>state.wrong[b.id]-state.wrong[a.id]);$('wrongList').innerHTML=filtered.length?filtered.map(q=>`<div class="wrong-item"><div class="wrong-head"><span class="tag">${moduleById(q.moduleId).name}</span><b>错 ${state.wrong[q.id]} 次</b></div><p>${escapeHtml(q.question)}</p><small>${q.ref} · ${q.type==='multiple'?'多选':'单选'}</small></div>`).join(''):'<div class="empty">暂无错题，继续保持。</div>'}
function renderStats(){$('statsAnswered').textContent=state.answered;$('statsCorrect').textContent=state.correct;$('statsRate').textContent=state.answered?`${Math.round(state.correct/state.answered*100)}%`:'—';$('moduleStats').innerHTML=bank.modules.map(m=>{const stats=moduleStat(m.id),rate=stats.answered?`${Math.round(stats.correct/stats.answered*100)}%`:'—',seen=moduleQuestions(m.id).filter(q=>state.seen[q.id]).length;return`<div class="stat-row"><div><b>${m.order}. ${m.name}</b><small>已覆盖 ${seen} / ${m.questionCount} 题</small></div><strong>${rate}</strong></div>`}).join('')}
function showView(name){if(name==='quiz'&&!state.activeSession){showToast('请先从题库选择一个类别');name='home'}document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==`${name}View`));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.querySelector('.bottom-nav').classList.toggle('hidden',name==='plan');if(name==='home')renderHome();if(name==='quiz')renderQuestion();if(name==='wrong')renderWrong();if(name==='stats')renderStats();window.scrollTo({top:0,behavior:'smooth'})}
function showToast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),1800)}function escapeHtml(value){const d=document.createElement('div');d.textContent=value;return d.innerHTML}function isStandalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}function updateInstall(){$('installTip').classList.toggle('show',!isStandalone());$('networkState').textContent=navigator.onLine?'已联网 · 离线资源将自动更新':'当前离线 · 仍可继续刷题'}
function bindEvents(){document.addEventListener('click',e=>{const module=e.target.closest('[data-module]');if(module){createSession(module.dataset.module);return}const option=e.target.closest('[data-option]');if(option){toggleOption(Number(option.dataset.option));return}const filter=e.target.closest('[data-wrong-filter]');if(filter){wrongFilter=filter.dataset.wrongFilter;renderWrong();return}const nav=e.target.closest('[data-view]');if(nav){showView(nav.dataset.view);return}const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;if(action==='show-plan')showView('plan');if(action==='show-home'||action==='pause')showView('home');if(action==='resume')resumeSession();if(action==='previous')moveQuestion(-1);if(action==='next')moveQuestion(1);if(action==='submit-multiple')submitAnswer([...pendingMulti]);if(action==='practice-wrong')createSession(wrongFilter,'wrong');if(action==='reset'&&confirm('确定清空当前浏览器里的全部学习记录吗？')){localStorage.removeItem(STATE_KEY);location.reload()}});const card=$('questionCard');card.addEventListener('touchstart',e=>{const t=e.changedTouches[0];touchStart={x:t.clientX,y:t.clientY,time:Date.now()}},{passive:true});card.addEventListener('touchend',e=>{if(!touchStart)return;const t=e.changedTouches[0],dx=t.clientX-touchStart.x,dy=t.clientY-touchStart.y,elapsed=Date.now()-touchStart.time;touchStart=null;if(elapsed<700&&Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.25)moveQuestion(dx>0?-1:1)},{passive:true});addEventListener('online',updateInstall);addEventListener('offline',updateInstall)}
async function init(){try{const response=await fetch('./data/questions.json',{cache:'no-cache'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const meta=await response.json(),files=meta.modules.map(m=>meta.questionFiles[m.id]),parts=await Promise.all(files.map(async file=>{const res=await fetch(file,{cache:'no-cache'});if(!res.ok)throw new Error(`${file}: HTTP ${res.status}`);return res.json()}));bank={...meta,questions:parts.flatMap(part=>part.questions)};questionsById=new Map(bank.questions.map(q=>[q.id,q]));loadState();if(state.activeSession){state.activeSession.questionIds=state.activeSession.questionIds.filter(id=>questionsById.has(id));if(!state.activeSession.questionIds.length)state.activeSession=null}bindEvents();renderHome();updateInstall();$('loading').classList.add('hidden');$('app').classList.remove('hidden');if('serviceWorker'in navigator&&location.protocol!=='file:'){const register=()=>navigator.serviceWorker.register('./sw.js').catch(()=>{});document.readyState==='complete'?register():addEventListener('load',register,{once:true})}}catch(error){$('loading').innerHTML='<b>题库加载失败，请联网刷新后重试。</b>';console.error(error)}}
init();
